22 77/main page
polygonov/naruto-runner pull request #11
Opened 2023-02-13 16:33 UTC by uliasavi

### Создание главной страницы

### Скриншоты/видяшка

https://user-images.githubusercontent.com/63160106/218516134-c57de6c0-1234-47ac-acb2-a2c6f317f737.mp4

### TBD (если есть)

2023-02-13 18:31 UTC, elaineir commented on packages/client/src/components/Button/index.tsx
> +  onClick?: () => void
onClick уже типизирован в `ButtonHTMLAttributes<HTMLButtonElement>` и доступен, нужно удалить кастомную типизацию

2023-02-13 18:31 UTC, elaineir commented on packages/client/src/components/Logo/index.css
> +  font-family: NinjaNaruto;
Для шрифта есть css-переменная `--font-naruto` с дополнительными безопасными шрифтами
```suggestion
  font-family: var(--font-naruto);
```

2023-02-13 18:31 UTC, elaineir commented on packages/client/src/pages/Main/index.tsx
> +export function MainPage() {
Лучше расположить контент главной страницы непосредственно в этом компоненте
Сейчас `MainPage` является лишней оберткой над `Main`

2023-02-13 20:01 UTC, uliasavi commented on packages/client/src/components/Logo/index.css
> +  background-clip: text;
https://developer.mozilla.org/ru/docs/Web/CSS/background-clip#совместимость_с_браузерами

2023-02-14 07:46 UTC, elaineir approved these changes

2023-02-14 13:25 UTC, MikeDevice commented
Блиииин. Как красиво! Кто у вас дизайнит это всё? Мне очень нравится идея и дизайны. Очень хочу увидеть игру цеником

2023-02-14 13:44 UTC, MikeDevice requested changes
В целом ок, но есть замечания

2023-02-14 13:44 UTC, MikeDevice commented on packages/client/.eslintignore
> +dist
👍

2023-02-14 13:44 UTC, MikeDevice commented on packages/client/src/components/Logo/index.css
> +  font-family: var(--font-naruto);
🤣  норм! Даже не знал, что есть такой шрифт. Думал, название игры -- это картинка

2023-02-14 13:44 UTC, MikeDevice commented on packages/client/src/components/Logo/index.tsx
> +      <div className='logo-text'>runner</div>
не. так не круто. По семантике нельзя рвать единый текст. Лучше напиши эти два слова в одном диваке, а в цсс пропиши `white-space: break-spaces`

2023-02-14 13:44 UTC, MikeDevice commented on packages/client/src/components/Logo/index.tsx
> +      <div className='logo-text'>runner</div>
тогда визуально всё останется так (междустрочный интервал через line-height подтюнить можно)

2023-02-14 13:44 UTC, MikeDevice commented on packages/client/src/pages/Main/index.css
> +  justify-content: center;
сейчас не придираюсь. просто совет на будущее: flex лучше использовать для точечных стилей, а не для всего каркаса страницы. 

<img width="765" alt="image" src="https://user-images.githubusercontent.com/7154108/218755240-d8f238f2-9332-403a-95eb-2f8e85b0e8b8.png">

https://htmlacademy.ru/blog/html/flexbox-vs-grid

2023-02-14 13:44 UTC, MikeDevice commented on packages/client/src/pages/Main/index.tsx
> +        {!isAuth && <Button text="Войти" onClick={moveToLoginPage} view="secondary" />}
заменить на ссылку. кнопка с navigate -- антипаттерн.

https://htmlacademy.ru/blog/html/links-or-buttons

2023-02-14 13:44 UTC, MikeDevice commented on packages/client/src/pages/Main/index.tsx
> +  }
нужно обернуть в `useCallback`. Ваша `Button` обёрнута в useMemo, потому нужно "уважать" её желания не рендериться каждый раз)

2023-02-15 09:13 UTC, MikeDevice approved these changes
Можно поправить коммент, если хочешь

2023-02-15 09:13 UTC, MikeDevice commented on packages/client/src/components/Logo/index.tsx
> +      <div className='logo-text'>{"Naruto\nrunner"}</div>
я не совсем это имел ввиду) это можно сделать на уровне вёрстки: https://developer.mozilla.org/ru/docs/Web/HTML/Element/br

2023-02-15 09:15 UTC, MikeDevice commented on packages/client/src/components/Logo/index.tsx
> +      <div className='logo-text'>{"Naruto\nrunner"}</div>
Но br тоже не идеал. С ним тоже есть проблемы. Идеал тут -- задать тексту контейнер, который будет выравнивать текст, но это уже другая история.

2023-02-15 09:35 UTC, merged