feat(LoginForm): Сделал форму и страницу авторизации
polygonov/naruto-runner pull request #12
Opened 2023-02-13 20:47 UTC by vmescher

Сделал форму авторизации

2023-02-14 13:06 UTC, MikeDevice requested changes

2023-02-14 13:06 UTC, MikeDevice commented on packages/client/src/components/forms/Login/index.tsx
> +    }
Формик сам умеет в эту логику. Почитай про свойство touched у Формика. Там очень много разных подходов. Выбирай, какой нравится. Очень удобно. Начать можешь отсюда https://formik.org/docs/guides/validation#when-does-validation-run

2023-02-14 13:06 UTC, MikeDevice commented on packages/client/src/components/forms/Login/index.tsx
> +      setTimeout(() => actions.setSubmitting(false), 1000)
зачем таймаут?

2023-02-14 13:06 UTC, MikeDevice commented on packages/client/src/components/forms/Login/index.tsx
> +      }
можно вынести этот фрагмент кода выше в переменную, обёрнутую в useMemo. Хотя форма у вас не обёрнута в memo, так что толку от этого не будет

2023-02-14 13:06 UTC, MikeDevice commented on packages/client/src/components/forms/Login/index.tsx
> +      formItems={
я думаю, что слишком громоздко получается. Лучше было бы с children, как изначально было.

2023-02-14 14:30 UTC, vmescher commented on packages/client/src/components/forms/Login/index.tsx
> +      setTimeout(() => actions.setSubmitting(false), 1000)
Я для примера, и лог тоже вывел для этого. Как аи прикручивать будем уберу)

2023-02-14 16:13 UTC, elaineir commented on packages/client/src/components/forms/Login/index.tsx
> +    .min(5, 'Минимальное кол-во символов: 5')
Хорошо бы еще вынести сам конфиг валидации для полей, чтобы потом переиспользовать его в профиле

2023-02-14 20:39 UTC, vmescher commented on packages/client/src/components/forms/Login/index.tsx
> +            onClick={() => navigate(RoutesNameList.Registration)}
Подготовим отдельный компонент под ссылку

2023-02-15 15:14 UTC, MikeDevice requested changes
реши конфликты

2023-02-16 09:37 UTC, MikeDevice approved these changes

2023-02-16 14:01 UTC, merged