feature/22-87: регистрация подключена к api, добавлен redux
polygonov/naruto-runner pull request #16
Opened 2023-02-21 21:00 UTC by elaineir

### Какую задачу решаем
- подключаем регистрацию к api практикума
- сделана заготовка для `useAuth` хука, будут добавлены доп. методы для работы с авторизацией
- `userStubFileds` нужен, чтобы рега на api практикума прошла успешно с нашим небольшим набором полей. Возможно напишем свою авторизацию в 7-8 спринте

2023-02-24 12:53 UTC, MikeDevice requested changes
Все реально очень круто! Мне нравится то, в каком стиле ты пишешь и проектируешь код. Но есть еще куда расти

2023-02-24 12:53 UTC, MikeDevice commented on .gitignore
> +package-lock.json
Ага. Забыл. У вас же ярн. Тогда откуда и как появился в репе этот файл?

2023-02-24 12:53 UTC, MikeDevice commented on packages/client/src/utils/trimData.ts
> +export const trimData = (data: Record<string, unknown>) => {
Люблю такие хелперы 👍

2023-02-24 12:53 UTC, MikeDevice commented on packages/client/src/store/user/thunk.ts
> +      return rejectWithValue((err as ApiErrorResponse).reason)
Смотри. У тебя все санки имеют копипасту: у них у всех есть try catch и они все одинаковые. Давай сделаем хелпер, который будет содержать эту логику?

2023-02-24 12:53 UTC, MikeDevice commented on packages/client/src/store/user/thunk.ts
> +      return rejectWithValue((err as ApiErrorResponse).reason)
В идеале я вижу это так, чтобы у тебя была своя функция createThunk

2023-02-24 12:53 UTC, MikeDevice commented on packages/client/src/store/user/thunk.ts
> +      return rejectWithValue((err as ApiErrorResponse).reason)
Еще было бы классно, чтобы тебе н приходилось приводить тип ошибки. Классно, если бы Апи метод сам бы возвращал ошибку в уже верном типе

2023-02-24 12:53 UTC, MikeDevice commented on packages/client/src/store/user/slice.ts
> +      state.error = (payload as string) ?? 'Что-то пошло не так'
Не хочется везде дублировать текст ошибки

2023-02-24 12:53 UTC, MikeDevice commented on packages/client/src/store/index.ts
> +export const useAppSelector: TypedUseSelectorHook<AppState> = useSelector
Тут все четко 😎

2023-02-24 12:53 UTC, MikeDevice commented on packages/client/src/api/base/index.ts
> +  protected async checkServerResponse<T>(
Название функции не соответствует тому, что она делает. Давая ее назовем handleServerResponse или как-то так?

2023-02-24 12:53 UTC, MikeDevice commented on packages/client/src/store/auth/selectors.ts
> +export const selectError = (state: AppState) => state.auth.error
Ты же создала useAppSelector. Почему не юзаешь его тут и всюду?

2023-02-24 12:53 UTC, MikeDevice commented on packages/client/src/store/auth/selectors.ts
> +export const selectError = (state: AppState) => state.auth.error
Ааа. Это хук. Ну да) расходимся 🙈

2023-02-24 12:53 UTC, MikeDevice commented on packages/client/src/pages/Registration/index.tsx
> +  return <RegistrationForm handleRegister={handleRegister} />
Вот это костыль. Это должно решаться на уровне роутера, а не в приложении. Но в данный момент, это не такая уж тривиальная задача, так что в целом не настаиваю

2023-02-24 12:53 UTC, MikeDevice commented on packages/client/src/hooks/useAuth.ts
> +}
👍

2023-02-24 12:53 UTC, MikeDevice commented on packages/client/src/api/auth/index.ts
> +  }
Не нравится мне копипаста в методах. Но не настаиваю

2023-02-24 18:13 UTC, MikeDevice commented on packages/client/src/pages/Registration/index.tsx
> +  return <RegistrationForm handleRegister={handleRegister} />
А костыль это потому, что сначала отрисуется RegistrationForm, а потом уже отработает useEffect. Выходит, зря рисовали RegistrationForm

2023-02-26 12:01 UTC, elaineir commented on .gitignore
> +package-lock.json
Второй раз прилетает от @vmescher, второй раз удаляем
Добавила в гитигнор, чтобы не высматривать файл в ПР

2023-02-26 12:02 UTC, elaineir commented on packages/client/src/store/user/thunk.ts
> +      return rejectWithValue((err as ApiErrorResponse).reason)
> Еще было бы классно, чтобы тебе н приходилось приводить тип ошибки. Классно, если бы Апи метод сам бы возвращал ошибку в уже верном типе

с этим не получилось разобраться, санки возвращают unknown, даже если изменить тип их стандартной ошибки

2023-02-27 09:25 UTC, MikeDevice requested changes
Ты прям идеально поняла, что я имел ввиду! Круто! Давай по-быстрому финалочку добьём!

2023-02-27 09:25 UTC, MikeDevice commented on packages/client/src/api/base/index.ts
> +    const response = await fetch(url, options)
а если запрос упадёт, мы тут не свалимся? тут не нужен try catch? или он где-то снаружи есть?

2023-02-27 09:25 UTC, MikeDevice commented on packages/client/src/router/Authorization.tsx
> +  requireUnAuth?: boolean
не могу понять, что за слово такое?) `require un auth` типо "Требуется отсутствие авторизации"?

2023-02-27 09:25 UTC, MikeDevice commented on packages/client/src/router/Authorization.tsx
> +  return <Outlet />
👍

2023-02-27 09:25 UTC, MikeDevice commented on packages/client/src/router/Authorization.tsx
> +  requireUnAuth?: boolean
Воооу. Теперь я запутался. У тебя есть ещё и `requireAuth`. А зачем их две? Разве понятие "требуется авторизация" не исключает понятие "авторизация не требуется"?

2023-02-27 09:25 UTC, MikeDevice commented on packages/client/src/hooks/useAuth.ts
> +    await dispatch(getUser()).unwrap()
а для чего `unwrap`? ты же никак результат не достаёшь

2023-02-27 09:25 UTC, MikeDevice commented on packages/client/src/hooks/useAuth.ts
> +    await dispatch(getUser()).unwrap()
я запутался. а как функция проверяет авторизацию? Мы просто дёргаем `getUser` и независимо от результата устанавливаем `setIsAuth` в `true`

2023-02-27 09:25 UTC, MikeDevice commented on packages/client/src/hocs/withAuth.tsx
> +  useLayoutEffect(() => {
мне просто интересно, а почему поменяла на useLayoutEffect? Дёргался экран?

2023-02-27 09:52 UTC, elaineir commented on packages/client/src/api/base/index.ts
> +    const response = await fetch(url, options)
Он попадает в catch санки, где реджектится с текстом ошибки

2023-02-27 09:53 UTC, elaineir commented on packages/client/src/router/Authorization.tsx
> +  requireUnAuth?: boolean
Есть ещё общие страницы, то есть тут три состояния:
- requireUnAuth -- требуется отсутствие авторизации для страницы регистрации и входа
- requireAuth -- требуется авторизация
- авторизация не важна

2023-02-27 09:54 UTC, elaineir commented on packages/client/src/hooks/useAuth.ts
> +    await dispatch(getUser()).unwrap()
> а для чего unwrap? ты же никак результат не достаёшь

Вообще это костыль, чтобы диспатчи прервались в случае ошибки)
Пыталась сделать через проверку ошибки в самом хэндлере, но она не успевает обновиться в сторе и все весело диспатчится паровозом. Пока не знаю, как это пофиксить
Ошибки ловятся в компоненте, где должен в дальнейшем вылезти тост

> я запутался. а как функция проверяет авторизацию? Мы просто дёргаем getUser и независимо от результата устанавливаем setIsAuth в true

Так устроено апи практикума. При реге мы получаем куку и затем должны сделать запрос за юзером. Если кука валидна, то юзер может считаться авторизованным.
Также если юзер повторно зашел на страницу, то нужно сделать запрос за юзером, чтобы убедиться, что кука все ещё валидна, иначе все остальные запросы отвалятся.

2023-02-27 09:55 UTC, elaineir commented on packages/client/src/hocs/withAuth.tsx
> +  useLayoutEffect(() => {
Да, немного дергался, ну и запрос уходит чуть раньше

2023-02-27 10:23 UTC, elaineir commented on packages/client/src/router/Authorization.tsx
> +  requireUnAuth?: boolean
А все, я поняла.
Общие же оборачиваются в этот компонент, так что да, requireUnAuth будет лишним
Поправлю

2023-02-27 10:49 UTC, MikeDevice commented on packages/client/src/hooks/useAuth.ts
> +    await dispatch(getUser()).unwrap()
А правильно ли я понял, что если эта строчка упадёт
```
await dispatch(getUser()).unwrap()
```
то следующая не вызовется?

Я просто пока не пойму следующего, как именно функция проверяет залогиненость. Мол. Ты дёргаешь юзера. Мы получаем ответ, что кука невалидна, что дальше? Почему не вызовется строка `await dispatch(setIsAuth(true))`?

2023-02-27 11:23 UTC, elaineir commented on packages/client/src/hooks/useAuth.ts
> +    await dispatch(getUser()).unwrap()
Да, `await dispatch(getUser()).unwrap()` падает и `checkAuth` завершается из-за ошибки. Проверка завершилась неуспешно, юзер остался неавторизованным и ограничен публичными страницами, пока не пройдёт авторизацию заново и не получит новую куку

![Снимок экрана от 2023-02-27 15-09-29](https://user-images.githubusercontent.com/75016726/221549004-df20ab52-b0cb-4dd3-bbb1-e5d9ced3fd83.png)

2023-02-27 12:55 UTC, MikeDevice commented on packages/client/src/hooks/useAuth.ts
> +    await dispatch(getUser()).unwrap()
> Проверка падает из-за .unwrap(), т.к. ошибка больше не ловится в диспатче

Костылище!) В этих местах всегда сложно: когда нужно передать управление из компонента в редакс. Будто колбэка не хватает, да?)

Смотри, как можно сделать не костыльно: нужно всю логику унести в thunk, а твоим недостающим колбэком будет selector

```
export const useAuth = () => {
  const dispatch = useAppDispatch()
  const isAuthChecking = useAppSelector(isAuthCheckingSelector)
  const isAuthCheckingDone = useAppSelector(isAuthCheckingDoneSelector)
  const isAuthorized = useAppSelector(isAuthorizedSelector)
  const authorizeError = useAppSelector(authorizedErrorSelector)

  const checkAuth = useCallback(() => {
    dispatch(checkAuth()) // await, кстати тут не нужны, dispatch же синхронный
  }, [dispatch])

  const handleRegister = useCallback(
    (data: RegisterPayload) => {
      dispatch(signUp(data)) // await, кстати тут не нужны, dispatch же синхронный
    },
    [dispatch]
  )

  return {
    ...
  }
}
```

Не буду детально расписывать. Верю, что поймёшь мою мысль. 
Мысль такая. Из компонента (в данном случае из хука) отправляется только экшны. Их ловит редакт, и отправляет на выполнение нужный `thunk`. В санке ты делаешь нужную тебе бизнес логику: дёргаешь апи юзера, проверяешь куку, и всё вот это вот. Этот санк в процессе будет кидать тебе другие экшны, сигназизирующие о том, что он ещё работает (isLoading, или что-то такое). Но когда он отработает, он кинет экшн `done`. В компоненте ты через селектор поймёшь, что санк отработал (`isAuthCheckingDone`), и через селектор `authorizeError` поймёшь была ли ошибка.

Так ты избавишься и от костыля и от того, что компонент знает про бизнес-логику

2023-02-27 12:57 UTC, MikeDevice commented on packages/client/src/hooks/useAuth.ts
> +    await dispatch(getUser()).unwrap()
реализовать можно как угодно, главное, чтобы была понятна суть

2023-02-27 19:24 UTC, elaineir commented on packages/client/src/hooks/useAuth.ts
> +    await dispatch(getUser()).unwrap()
Перенесла бизнес-логику в санки

2023-02-28 10:22 UTC, MikeDevice approved these changes
огонь!

2023-02-28 10:40 UTC, merged