22 5/forum
polygonov/naruto-runner pull request #17
Opened 2023-02-22 15:05 UTC by uliasavi

### 22-5 сверстан форум

### Скриншоты/видяшка (если есть)

![image](https://user-images.githubusercontent.com/63160106/220662496-a4f029b4-96ce-441c-87dc-ed0d1c6dd982.png)
![image](https://user-images.githubusercontent.com/63160106/220662636-78cd9abf-ecd9-48bd-b802-c67ee6120fe7.png)

2023-02-23 17:09 UTC, MikeDevice requested changes

2023-02-23 17:09 UTC, MikeDevice commented on packages/client/src/pages/Forum/parts/AddTopic/index.tsx
> +        <form action="#" method="post" className="add-topic__form">
Action не надо

2023-02-23 17:09 UTC, MikeDevice commented on packages/client/src/pages/Topic/index.tsx
> +      <div className="input-wrapper">input-wrapper</div>
Инпут будет позже?

2023-02-23 17:09 UTC, MikeDevice commented on packages/client/src/pages/Topic/Chat/index.tsx
> +  }
Тебе нужно объявить тип сообщения, чтоб юзать и тут и в массиве

2023-02-23 17:09 UTC, MikeDevice commented on packages/client/src/pages/Topic/Chat/index.tsx
> +          />
Если ифак вернет false, то тут будет пустой div -- нехорошо

2023-02-23 17:09 UTC, MikeDevice commented on packages/client/src/pages/Topic/Chat/index.css
> +.chat-wrapper .topic-chat {
Зачем увеличиваешь веса?

2023-02-23 17:09 UTC, MikeDevice commented on packages/client/src/pages/Topic/Chat/TypingPlace/index.tsx
> +        onClick={e => e.preventDefault}
😑😑😑

2023-02-23 17:09 UTC, MikeDevice commented on packages/client/src/pages/Topic/Chat/TypingPlace/index.tsx
> +    <form className="typing-place" action="#">
Зачем экшн?

2023-02-23 17:09 UTC, MikeDevice commented on packages/client/src/pages/Topic/Chat/TypingPlace/index.tsx
> +import './index.css'
Порядок

2023-02-23 17:09 UTC, MikeDevice commented on packages/client/src/pages/Topic/Chat/Message/Index.tsx
> +import './index.css'
Порядок

2023-02-23 17:09 UTC, MikeDevice commented on packages/client/src/pages/Topic/Chat/Message/index.css
> +.message-wrapper .user-wrapper {
Веса

2023-02-25 13:48 UTC, uliasavi commented on packages/client/src/components/MainLayout/index.css
> +  background-image: url(../../assets/images/background/Background.png);
можешь сказать точнее? я не понимаю о чем ты..

2023-02-25 14:09 UTC, uliasavi commented on packages/client/src/constant.ts
> +  Topic:`/forum/:id`
а как? есть страница форума с топиками, когда выбираешь конкретный топик - переходишь на страницу по айди

2023-02-25 18:04 UTC, MikeDevice commented on packages/client/src/constant.ts
> +  Topic:`/forum/:id`
а какой адрес у страницы форума с топиками?

2023-02-25 18:05 UTC, MikeDevice commented on packages/client/src/components/MainLayout/index.css
> +  background-image: url(../../assets/images/background/Background.png);
https://htmlacademy.ru/blog/html/retina

2023-02-25 18:52 UTC, uliasavi commented on packages/client/src/constant.ts
> +  Topic:`/forum/:id`
/forum

2023-02-25 20:10 UTC, uliasavi commented on packages/client/src/pages/Forum/parts/AddTopic/index.tsx
> +  const toggleShowAddTopicForm = () => {
я не понимаю почему. Я вроде прочитала теорию 5/6 го спринта, но не понимаю многих вещей. буду рада ссылочке

2023-02-25 20:11 UTC, uliasavi commented on packages/client/src/pages/Forum/parts/AddTopic/index.css
> +.input.big-box-size .input__control {
ну тут не вес, а добавление класса к обертке в которой надо изменить кое-что. а что не так?

2023-02-25 20:23 UTC, MikeDevice commented on packages/client/src/pages/Forum/parts/AddTopic/index.tsx
> +  const toggleShowAddTopicForm = () => {
https://habr.com/ru/post/529950/

2023-02-26 13:02 UTC, elaineir commented on packages/client/src/pages/Forum/parts/AddTopic/index.css
> +.input.big-box-size .input__control {
Тут лучше было бы добавить новый проп самому инпуту, например, `size`, и через него подставить нужный класс, чем вторгаться в его внутренние стили

2023-02-26 13:05 UTC, elaineir commented on packages/client/src/pages/Topic/Chat/Message/Index.tsx
> +        <div className="user-name">{userName}</div>
Хорошо бы использовать семантичные теги вместо диватоза здесь и ниже

2023-02-26 19:48 UTC, uliasavi commented on packages/client/src/pages/Topic/Chat/Message/Index.tsx
> +        <div className="user-name">{userName}</div>
например?

2023-02-26 20:02 UTC, uliasavi commented on packages/client/src/pages/Topic/Chat/Message/Index.tsx
> +        <div className="user-name">{userName}</div>
так как мы прокачиваем еще и софт скилы, предлагаю такой перефраз твоего комментария. 
"Я предлагаю использовать такие-то тэги..."

2023-02-27 08:53 UTC, elaineir commented on packages/client/src/pages/Topic/Chat/Message/Index.tsx
> +        <div className="user-name">{userName}</div>
> например?
Например, `<p>` для текстового контента
`<div>` не несет никакого смысла и используется в качестве контейнеров
https://html.spec.whatwg.org/#the-div-element

Семантика важна для поисковиков и скринридеров, тем более проект будет на SSR.
https://html.spec.whatwg.org/#text-level-semantics

> так как мы прокачиваем еще и софт скилы, предлагаю такой перефраз твоего комментария. "Я предлагаю использовать такие-то тэги..."

"Я считаю, я предлагаю" в ревью это плохой тон. Комментарии в ревью должны быть обезличенными и указывать на проблему или предлагать улучшение.

2023-02-27 09:34 UTC, MikeDevice approved these changes
Спасибо за 2х картинки!

Вопрос не к тебе, а в целом к команде: а почему вы практически не используете мощность TypeScript и пишете всё на чистом JS? Вам же самим сильно проще было бы, ну и плюс в реальной работе скорее всего у вас будет требование к использованию TypeScript

2023-02-27 09:34 UTC, MikeDevice commented on packages/client/src/components/MainLayout/index.css
> +}
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉  Спасибо!

2023-02-27 09:34 UTC, MikeDevice commented on packages/client/src/components/MainLayout/index.tsx
> +  { backGroundImage: string; backGroundImage2x: string; pageName: string }
background -- единое слово. Делать `G` большой не нужно)

2023-02-27 09:46 UTC, merged