Feature/22 7 game engine
polygonov/naruto-runner pull request #18
Opened 2023-02-26 09:27 UTC by polygonov

### Какую задачу решаем
Добавил стартовый набор игрового движка - анимация фона, анимация бега персонажа, прыжок.

### Скриншоты/видяшка (если есть)
https://user-images.githubusercontent.com/54527017/221402560-51357bb0-4624-4059-8c9c-67126d2e5b81.mp4

### TBD (если есть)
Требуется добавить препятствия (враги) и детекцию столкновения.

2023-02-27 09:02 UTC, MikeDevice commented
я просто мимо проходил и заценил видяшку. И, ребят. Это! Просто! Охеренно!

2023-02-27 20:50 UTC, elaineir commented on packages/client/src/components/Game/components/CanvasComponent/index.tsx
> +    const background = new Background(context)
`useEffect` в strict-режиме вызывается два раза и сейчас создает два цикла для `background` и `hero`, то есть под капотом крутится две версии игры (видно по айдишникам в консоли):
![Снимок экрана от 2023-02-27 23-50-15](https://user-images.githubusercontent.com/75016726/221668082-85de682f-545a-4d34-8011-2ab5016d2e46.png)

В проде должен создаться один цикл, но в девелопменте это может привести к неожиданным багам.

У меня тоже была такая проблема с движком, помог синглтон для движка и игровые статусы (running, paused, unmounted) для управления циклом рендера.

2023-02-27 20:50 UTC, elaineir commented on packages/client/src/components/Game/engine/Hero.ts
> +    window.addEventListener('keydown', this.onKeyDown)
Сейчас возникает утечка памяти из-за того, что обработчик навешивается каждый раз при вызове `new Hero()`

Можно сделать метод `unmount()`, в котором будет удаление обработчика, и вызывать его в `useEffect` в компоненте с канвой:

```TypeScript
useEffect(() => {
  // ...
  return () => hero.unmount()
}, [])
```

Так обработчик удалится при размонтировании компонента и утечки не будет

2023-02-27 20:50 UTC, elaineir commented on packages/client/src/components/Game/engine/Hero.ts
> +    const offsetTop = 220
Эти числа (`offsetTop`, `offsetLeft`, `movePartial`) повторяются в нескольких методах, и без вчитывания не понятно, нужно ли их менять во всех методах или все работает точечно

Их стоит вынести в константы, если они должны быть одинаковыми в разных методах

2023-02-27 20:50 UTC, elaineir commented on packages/client/src/components/Game/index.tsx
> +    <Fragment>
Фрагменты используются для оборачивания двух и более элементов, чтобы дать им общий "корень". Здесь только один `div`, поэтому можно их удалить

2023-02-27 20:50 UTC, elaineir commented on packages/client/src/pages/Game/index.tsx
> +    <Fragment>
Здесь тоже можно не использовать фрагмент

2023-03-24 14:57 UTC, MikeDevice commented
Ееее. Я ждал этот ПР! Ток реши конфликты сначала плиз

2023-03-24 15:24 UTC, MikeDevice requested changes
Не зови на ревью, если не прошли эти две проверки ![image](https://user-images.githubusercontent.com/7154108/227568403-99373984-0c94-4153-bf84-343391162c37.jpeg)

2023-03-24 15:40 UTC, polygonov commented
Извиняюсь, проверки билда прошли вот я и дернул. Поправил merge.

2023-03-24 17:11 UTC, MikeDevice requested changes
Смотри. В целом ПР очень классный, но есть места, которые прям странные по типу `if (this)`, которые надо переделать. Есть правки, которые чисто по желанию (касаемые архитекруты).

А вообще ты большой молодец. Очень красивый и довольно структурированный код

2023-03-24 17:11 UTC, MikeDevice commented on packages/client/src/components/Game/engine/Hero.ts
> +    window.addEventListener('keydown', this.onKeyDown)
Hero не должен знать про обработчики. Это должно рулиться на уровень выше.

2023-03-24 17:11 UTC, MikeDevice commented on packages/client/src/components/Game/engine/Hero.ts
> +    if (this.action === Action.Run && event.code === 'Space') {
тож самое, что и выше. Он не должен знать про коды клавиш

2023-03-24 17:11 UTC, MikeDevice commented on packages/client/src/components/Game/engine/Hero.ts
> +    if (this.action === Action.Up) {
выше коммент про ифаки

2023-03-24 17:11 UTC, MikeDevice commented on packages/client/src/components/Game/engine/Enemy.ts
> +    const varietyOfEnemy = 4
в константы выше вынести

2023-03-24 17:11 UTC, MikeDevice commented on packages/client/src/components/Game/engine/EnemyManager.ts
> +  }
вообще это выглядит как типичный хелпер, а не часть класса.

2023-03-24 17:11 UTC, MikeDevice commented on packages/client/src/components/Game/engine/EnemyManager.ts
> +    if (progress >= this.frameRate && this.collisionDetector !== undefined) {
можно же проще:
```diff
- this.collisionDetector !== undefined
+ this.collisionDetector
```

2023-03-24 17:11 UTC, MikeDevice commented on packages/client/src/components/Game/engine/EnemyManager.ts
> +          array.splice(index, 1)
внутри `forEach` менять массив плохая тема. Пробежись фильтром лучше

2023-03-24 17:11 UTC, MikeDevice commented on packages/client/src/components/Game/engine/Engine.ts
> +    this.enemyManager.generate()
generate -- это же то же по сути draw. Давай просто в массиве пробежимся по всем сущностям с методом draw и одной строкой всё вызовем?

2023-03-24 17:11 UTC, MikeDevice commented on packages/client/src/components/Game/engine/Engine.ts
> +    if (this && this.enemyManager !== undefined) {
странная тема на проверку this. Когда его может не быть?

2023-03-24 17:11 UTC, MikeDevice commented on packages/client/src/components/Game/engine/Engine.ts
> +    if (this && this.enemyManager !== undefined) {
можно без `!== undefined`

2023-03-24 17:11 UTC, MikeDevice commented on packages/client/src/components/Game/engine/Engine.ts
> +    if (this) {
странная тема на проверку this.

2023-03-24 17:11 UTC, MikeDevice commented on packages/client/src/components/Game/engine/Engine.ts
> +    this.hero.mount()
вот то место, где надо вещать обработчики для Hero и тд и тп

2023-03-25 07:56 UTC, MikeDevice commented on packages/client/src/components/Game/engine/Engine.ts
> +        this.hero.status = EngineStatus.Running
если у тебя в игре будет мильон объектов, то тут будет мильён строк. чтоб такого не было, надо иметь поле `gameItems: [background, hero, ...]` и бегать в цикле по нему

2023-03-25 14:16 UTC, polygonov commented on packages/client/src/components/Game/engine/Background.ts
> +    )
Background я рисую два раза (слева и справа) и двигаю обе картинки влево - когда левая картинка полностью уходит за пределы экрана (на экране видна остается только правая) - тогда я смещаю картинки снова вправо и опять левая видна на экране - правая за экраном справа, и снова сдвигаю их влево. Так получается зацикленное движение фона.

2023-03-25 14:22 UTC, polygonov commented on packages/client/src/components/Game/engine/EngineOptions.ts
> +  canvasWidth = 1920,
Да, я решил не делать адаптив, целевой моник фул хд - но небольшую настройку все таки сделал, для мониторов с меньшим расширением - канва всегда будет от 0, поэтому игрок будет в фокусе, разве что длинна игровой области будет чуть короче. Если же монитор больше full hd тогда канва будет отцентрована.

2023-03-25 14:55 UTC, MikeDevice commented on packages/client/src/components/Game/engine/Background.ts
> +    )
огонь

2023-04-02 15:55 UTC, polygonov commented on packages/client/src/components/Game/engine/Engine.ts
> +    this.enemyManager.generate()
generete это не только draw но и добавление врагов в массив врагов, а так же удаление врагов из этого списка если они уже вне границ экрана, и плюс это проверка на столкновение. поэтому просто вызвать draw у врагов не получится

2023-04-02 17:55 UTC, polygonov commented
Спасибо за ревью, большую часть замечаний постарался исправить. Некоторые подсказки пришлись прям очень в тему.

2023-04-02 19:56 UTC, MikeDevice approved these changes

2023-04-02 19:56 UTC, MikeDevice commented on packages/client/src/components/Game/engine/EnemyManager.ts
> +          array.splice(index, 1)
ты же splice так и не убрал :) то есть ты так же продолжаешь менять массив) Но в целом, если хочешь так, делай)

Проблема тут в неявности. Filter -- это функция высшего порядка (привет, функциональное программирование). От filter никто не ожидает, что из массива, в котором 100 элементов, будет всего 3 итерации.

2023-04-03 14:07 UTC, merged