feature/22-88: профиль подключен к api практикума
polygonov/naruto-runner pull request #20
Opened 2023-03-04 12:25 UTC by elaineir

### Какую задачу решаем
- подключает профиль к api
- можно менять данные, аватар, пароль

Предварительно надо зарегистрироваться (логин пока не работает)

2023-03-06 12:34 UTC, MikeDevice requested changes

2023-03-06 12:34 UTC, MikeDevice commented on packages/client/src/pages/Profile/components/ProfileForm/index.tsx
> +    const userError = useAppSelector(selectUserError)
есть другой вариант: когда у тебя селектор, который получает корень твоего юзера: 
```
const { user, isAvatarLoading, ... } = useAppSelector(selectUserData)
```

2023-03-06 12:34 UTC, MikeDevice commented on packages/client/src/pages/Profile/components/ProfileForm/index.tsx
> +    const userError = useAppSelector(selectUserError)
на твой вкус

2023-03-06 12:34 UTC, MikeDevice commented on packages/client/src/pages/Profile/components/ProfileForm/index.tsx
> +        !userError
ужасный ифак. давай вынесем это значение в переменную, чтоб название переменной говорила о том, что оно в себе содержит?

2023-03-06 12:34 UTC, MikeDevice commented on packages/client/src/pages/Profile/components/ProfileForm/index.tsx
> +            user?.login ?? 'login'
а почему показываем слово login незалогину?

2023-03-07 15:20 UTC, elaineir commented on packages/client/src/store/user/thunk.ts
> +  }
нет, при смене пароля ничего не возвращается, только Ок или ошибка

2023-03-07 15:23 UTC, elaineir commented on packages/client/src/pages/Profile/components/ProfileForm/index.tsx
> +            user?.login ?? 'login'
Незалогин сюда не попадет, это заглушка на случай, если вдруг по какой-то причине у юзера не будет логина. Маловерятно, но просто на всякий

2023-03-07 15:35 UTC, MikeDevice approved these changes
огонь

2023-03-07 15:35 UTC, MikeDevice commented on packages/client/src/pages/Profile/components/ProfileForm/index.tsx
> +      if (isAllRequestsFulfilled) {
`areAll`. Ох уж этот английский))

2023-03-07 15:35 UTC, MikeDevice commented on packages/client/src/api/base/index.ts
> +    if (!isGetMethod && data && contentType === 'json') {
этот ифак можно внутрь предыдущего вставить. логика не изменится, но станет более читаемо

2023-03-07 15:35 UTC, MikeDevice commented on packages/client/src/api/base/index.ts
> +    if (!isGetMethod && data && contentType === 'json') {
на твой вкус

2023-03-07 15:44 UTC, merged