Feature/22 86 auth
polygonov/naruto-runner pull request #23
Opened 2023-03-08 18:21 UTC by vmescher

Сделал авторизацию пользователя

2023-03-08 19:37 UTC, elaineir reviewed
Нужно починить падающий тест в `LoginForm.test.tsx`

2023-03-08 19:37 UTC, elaineir commented on packages/client/src/api/auth/index.ts
> +      data: { ...trimData(payload) },
```suggestion
      data: trimData(payload),
```

Здесь можно не создавать новый объект, а сразу передать результат функции

2023-03-08 19:37 UTC, elaineir commented on packages/client/src/main.tsx
> +// startServiceWorker()
А для чего закомментировано? Что-то поломалось?

2023-03-09 06:39 UTC, MikeDevice requested changes
Не зови ревьюить, если CI красный, плиз

2023-03-26 19:26 UTC, merged