Feature/22 101 api forum
polygonov/naruto-runner pull request #32
Opened 2023-04-04 21:14 UTC by vmescher

API для форума

Я не уверен, что оно все безошибочно работает. Но делать тут очень много, и мне бы хотелось продемонстрировать, что уже сделано

Подключил pfAdmin для удобного просмотра и редактирования таблиц
Обернул запуск сервера в класс
Написал модели, контроллеры и роуты для форума

2023-04-05 11:02 UTC, MikeDevice requested changes

2023-04-05 11:02 UTC, MikeDevice commented on packages/server/src/services/CommentsService.ts
> +        status: false,
ааа. понял. удалено оно или нет, чтобы не удалять на самом деле.

2023-04-05 11:02 UTC, MikeDevice commented on packages/server/src/services/CommentsService.ts
> +          id,
а вот тут вопрос. А что получается, что у комментов нет оригинальных id? То есть в двух топиках у комментов айдишники могут пересекаться?

Это не очень трушная система. У каждой сущности должен быть свой уникальный id

2023-04-05 11:02 UTC, MikeDevice commented on packages/server/src/services/topicsService.ts
> +      return Topic.findAll({
то же, что и выше

2023-04-06 12:36 UTC, vmescher commented on packages/server/src/services/CommentsService.ts
> +          id,
У них уникальный id, я зачем то это сюда тоже добавил

2023-04-06 12:36 UTC, vmescher commented on packages/server/src/services/CommentsService.ts
> +        status: false,
Да, я поэтому решил не использовать delete, а именно post. Тк удаление не происходит на самом деле

2023-04-06 18:07 UTC, vmescher commented on packages/server/src/controllers/commentsController.ts
> +      message: message ? String(message) : undefined,
Там не только string но еще string | QueryString.ParsedQs | string[] | QueryString.ParsedQs[] | undefined, поэтому ts ругался

2023-04-10 10:10 UTC, MikeDevice approved these changes
сорян, провтыкал –– ПР не сразу увидел.

2023-04-10 10:10 UTC, MikeDevice commented on packages/server/src/server.ts
> +    router.use('^/$', this.serverRenderer.bind(this))
так как оно теперь снизу, то релулярку можно ослабить до `/` -- в целом, так и правильно делать, так как рисовать страницу нужно не только по корню (обычно)

2023-04-11 11:38 UTC, vmescher commented on packages/server/src/server.ts
> +    router.use('^/$', this.serverRenderer.bind(this))
Понял, поправлю

2023-04-12 17:36 UTC, merged