Доработки по АПИ Форума
polygonov/naruto-runner pull request #38
Opened 2023-04-17 18:48 UTC by vmescher

Доработал АПИ форума, сделал сохранение пользователей в отдельную таблицу для вывода информации об авторе темы или комментария, добавил проверку авторизации пользователей и сделал проксирование запросов

2023-04-18 11:06 UTC, elaineir commented on packages/client/src/constant.ts
> +  process.env.NODE_ENV === 'development' ? 'http://localhost:3001' : ''
Порт для локалхоста лучше брать из env-переменной

2023-04-18 11:06 UTC, elaineir commented on packages/client/vite.config.ts.timestamp-1680545013132.mjs
> +// ../client/vite.config.ts
Не уверена, что нам нужен этот файл. Откуда он взялся?)

2023-04-18 11:06 UTC, elaineir commented on packages/server/src/middlewares/authMiddleware.ts
> +  baseURL: 'https://ya-praktikum.tech',
`'https://ya-praktikum.tech'` лучше вынести в константы, строка используется в двух мидлварях

2023-04-18 12:40 UTC, MikeDevice requested changes

2023-04-18 12:40 UTC, MikeDevice commented on packages/client/src/constant.ts
> +  process.env.NODE_ENV === 'development' ? 'http://localhost:3001' : ''
Подожди, а почему если не development, то пустая строка?

2023-04-18 12:40 UTC, MikeDevice commented on packages/server/src/middlewares/proxyMiddleware.ts
> +      }
ух ты. а что это за логика такая? Если дёрнули урл `/auth/user`, то он запишет в базу то, что отдал практикум? Но зачем?

2023-04-18 12:40 UTC, MikeDevice commented on packages/server/src/middlewares/proxyMiddleware.ts
> +      }
Мол, ты же и так получил юзера из практикума, зачем дополнительно складывать в свою базу. Как ты потом используешь это?

2023-04-19 17:17 UTC, vmescher commented on packages/server/src/middlewares/proxyMiddleware.ts
> +      }
Я планирую положить к ним текущую тему пользователя и быстрее обрабатывать запросы на форум, не запрашивать каждого комментатора у Яндекса, а из своей базы их выдавать

2023-04-19 17:19 UTC, vmescher commented on packages/client/src/constant.ts
> +  process.env.NODE_ENV === 'development' ? 'http://localhost:3001' : ''
Чтоб просто на текущий домен обращаться и все

2023-04-19 19:57 UTC, vmescher commented
Исправил ошибки, доделал темизацию для наглядности происходящего. Нашел баги в предыдущих контроллерах и тоже поправил

2023-04-20 10:09 UTC, MikeDevice approved these changes

2023-04-21 02:10 UTC, merged