Header+main layout
polygonov/naruto-runner pull request #7
Opened 2023-02-12 09:05 UTC by uliasavi

### 22-71 22-58 Верстка основного лайаута, хэдэра и роутинг

2023-02-12 10:21 UTC, elaineir approved these changes
Хорошая работа, ставлю апрув! Можно внести несколько улучшений по коду

2023-02-12 10:21 UTC, elaineir commented on packages/client/src/App.tsx
> +  const pathname = useLocation().pathname
Можно деструктурировать
```suggestion
  const { pathname } = useLocation()
```

2023-02-12 10:21 UTC, elaineir commented on packages/client/src/App.tsx
> +    <MainLayout background={`${pathname}`}>
useLocation в кач-ве pathname возвращает строку, поэтому можно сразу отправить ее в проп
```suggestion
    <MainLayout background={pathname}>
```

2023-02-12 10:21 UTC, elaineir commented on packages/client/src/components/MainLayout/index.tsx
> +  getImageName(): string {
Можно вынести в объект выше компонента

```TypeScript
const imageNames: { [key: string]: string } = {
  '/': 'Main',
  '/forum': 'Main',
  '/login': 'Login',
  '/leaderboard': 'Leaderboard',
  '/profile': 'Profile',
}
```

2023-02-12 10:21 UTC, elaineir commented on packages/client/src/components/MainLayout/index.tsx
> +    return `src/assets/images/background/${this.getImageName()}.png`
И использовать здесь как
```suggestion
    return `src/assets/images/background/${imageNames[this.props.background]}.png`
```

2023-02-12 17:22 UTC, vmescher commented on packages/client/src/components/MainLayout/index.tsx
> +      </div>
Я бы лучше немного поменял разметку( Если представить адаптив, то так будет очень сложно все сделать красиво. В идеале взять отдельно картинки фона с иероглифами и фона с персонажами, думаю у Игоря должны быть исходники. Тогда элементу с классом layout мы задаем по умолчанию фон с иероглифами. Фон с картинкой вставляем абсолютом к правому углу, тянем по высоте и задаем ширину 75% и используем clip-path, чтоб создать угол и filter: drop-shadow чтоб сделать красную тень. Самому изображению ширину и высоту на 100%, object-fit: cover. 

Элементу с классом layout лучше не задавать никаких отступов, нужна только высота и ширина 100%, display: flex. Соответственно layout__content получает flex: 1 1 auto, padding: 35px 0

wrapper можно выделить в отдельный компонент, у которого базого в стилях будет padding: 0 120px. И использовать его нужно внутри самих элементов таких как хедер, экраны и тд. 

При такой реализации проще будет проконтролировать соотношение бэкграунда к контенту, и мы сможем без особых усилий скрыть его в адаптиве. 

`<div className='layout>
     <div className='layout__body>
          <HeaderComponent />

          { props.children }
     </div>
     <picture className='layout__bg'>
         <img className='layout__bg-image' src={this.getBackgroundImgPath()} />
     </picture>
</div>`

2023-02-12 17:22 UTC, vmescher commented on packages/client/src/index.css
> +  width: 100% !important;
!important здесь лишний. Достаточно будет html и body задать height: 100%,

2023-02-12 17:22 UTC, vmescher commented on packages/client/src/components/MainLayout/index.tsx
> +    return `src/assets/images/background/${this.imageNames[this.props.background]}.png`
Так мы не сможем переключать фоны. Лучше задать базовый путь и привязать названия картинок к соответствующим страницам

2023-02-12 18:39 UTC, uliasavi commented on packages/client/src/components/MainLayout/index.tsx
> +      </div>
ну это в идеале и адаптив мы не делаем. тогда зачем заморачиваться? я хотела разбить на картинку и фон, но в исходном это одна картинка. это того не стоит. задачи такой не стоит. я сделаю свою часть работы хорошо. но отдавать этому все время - я не буду.

2023-02-12 18:40 UTC, uliasavi commented on packages/client/src/components/MainLayout/index.tsx
> +    return `src/assets/images/background/${this.imageNames[this.props.background]}.png`
что значит не смоем задавать фоны? это как раз для того и есть. тут смотрим что за страница открыта и под нее берется фон.

2023-02-12 18:43 UTC, uliasavi commented on packages/client/src/index.css
> +  width: 100% !important;
!important уберу. копирнула со стандартных стартовых стилей и не заметила.

2023-02-12 19:06 UTC, elaineir commented on packages/client/src/components/MainLayout/index.tsx
> +    return `src/assets/images/background/${this.imageNames[this.props.background]}.png`
Кстати да, Владислав прав. При билде картинки не подтянутся, если их заранее не импортировать

Например, `import mainBackground from '../../assets/images/background/Main.png'`
И этот `mainBackground` уже можно использовать в компоненте

2023-02-13 08:34 UTC, uliasavi commented on packages/client/src/components/MainLayout/index.tsx
> +    return `src/assets/images/background/${this.imageNames[this.props.background]}.png`
я не понимаю о чем вы, как это исправить?

2023-02-13 09:14 UTC, uliasavi commented on packages/client/src/components/MainLayout/index.tsx
> +    return `src/assets/images/background/${this.imageNames[this.props.background]}.png`
@MikeDevice спасибо, отлично, я тогда вечером настрою автодеплой и посмотрим результат.

2023-02-13 13:50 UTC, MikeDevice requested changes
1. Разобраться с картинками.
2. Почитать комменты

2023-02-13 13:50 UTC, MikeDevice commented on packages/client/src/components/Header/NavLink/NavLink.test.tsx
> -  })
а почему тест убрали?

2023-02-13 13:50 UTC, MikeDevice commented on packages/client/src/components/Header/NavLink/NavLink.test.tsx
> -  })
Ааа. Понял. Удалили такой функционал. Ок.

2023-02-13 13:50 UTC, MikeDevice commented on packages/client/src/components/Header/index.tsx
>  export default function HeaderComponent() {
А почему без типов везде? На `TypeScript` же пишем.

2023-02-13 13:50 UTC, MikeDevice commented on packages/client/src/components/Header/index.tsx
>      <header className="header-component">
`<li key={data.text}>` -- давай в качестве ключа подавать урл, а не текст. Так будет вернее, так как урлы всегда уникальные для разных страниц, а вот текст может и совпасть.

2023-02-13 13:50 UTC, MikeDevice commented on packages/client/src/components/MainLayout/index.tsx
> +    '/profile': 'Profile',
у нас получается, что роуты дублируются. И тут, и в самом роутере. Давайте заведём хэш с урлами и просто будем юзать его везде, где нужны доступы к урлам:

```ts
export const Routes = {
  Main: '/',
  Forum: '/forum'
}
```

Можно через `enum`, можно через `Record`.

2023-02-13 13:50 UTC, MikeDevice commented on packages/client/src/components/MainLayout/index.tsx
> +    return `src/assets/images/background/${this.imageNames[this.props.background]}.png`
Ни один компонент не должен знать про пути в приложении. Всё это надо выносить в конфиги. Например так:

```ts
// config.ts
export const imagesBasePath = 'src/assets/images/background/'
```

Или даже круче
```ts
// config.ts
export const getImagePath = (imageName: string) => {
  return `src/assets/images/background/${imageName}`;
}
```

А тут его уже использовать.

2023-02-13 13:50 UTC, MikeDevice commented on packages/client/src/pages/Forum/index.tsx
> +    </Fragment>
На случай, если не знаешь: можно фрагмент так писать
```diff
- <Fragment>
+ <>
  <div> Forum</div>
- </Fragment>
+ </>
```

2023-02-13 13:50 UTC, MikeDevice commented on packages/client/src/components/MainLayout/index.tsx
> +        }}>
Есть второй способ сделать это. Он более громоздский в написании, однако производительнее.

```
// type = 'forum'

className={classNames(
  'layout',
  { [`layout_type_${type}`]: true }
)}

.layout_type_forum {
  background-image: url(...)
}

.layout_type_profile {
  background-image: url(...)
}

и тд.
```

Не прошу переписать. Просто рассказываю, так как использование `style` не является хорошим тоном.

2023-02-13 14:45 UTC, uliasavi commented on packages/client/src/components/MainLayout/index.tsx
> +    return `src/assets/images/background/${this.imageNames[this.props.background]}.png`
задеплоить может только хозяин репы, я проверила. там и посмотрим картинки. но все должно работать. если нет, то я обязательно исправлю

2023-02-13 15:02 UTC, MikeDevice commented on packages/client/src/components/MainLayout/index.tsx
> +    return `src/assets/images/background/${this.imageNames[this.props.background]}.png`
чтоо? деплоить должен бот. может ты имеешь ввиду настройку автодеплоя?

2023-02-13 15:07 UTC, MikeDevice approved these changes

2023-02-13 15:09 UTC, merged